### PR TITLE
obs-xdg-portal: init

### LINKED ISSUE #236: package request: obs-xdg-portal
https://gitlab.gnome.org/feaneron/obs-xdg-portal

cc: @ashkitten

### PR DESCRIPTION
**Pull request by berbiche**
Closes #236

I couldn't select a window under Sway (as expected) so I tested with Gnome instead.
Window sharing under Gnome:

Desktop sharing under Gnome:

Screenshot 2020-11-06 00-58-51

### CODE REVIEW

**Comment by berbiche** [comment]
The version number shown in obs' title bar is an addition from my overlay:

``` nix
final: prev:

with prev.lib;

let
  version = "26.0.0-dmabuf";
  versionFlag = "-DOBS_VERSION_OVERRIDE";
in
{
  obs-studio = prev.obs-studio-dmabuf.overrideAttrs (old:
    let
      cmakeFlags = old.cmakeFlags or [ ];
      hasFixedVersion = any (hasPrefix versionFlag) cmakeFlags;
    in optionalAttrs (!hasFixedVersion) {
      cmakeFlags = cmakeFlags ++ [ "${versionFlag}=${version}" ];
    });
}

```

**Comment by colemickens** [comment]
Can you give me the rundown on the difference in this obs-studio branch vs the one I have in the tree already? Thanks!

**Comment by berbiche** [comment]
The `egl-dmabuf` is required by `obs-xdg-portal` otherwise it doesn't compile.

**Comment by berbiche** [comment]
@colemickens ping

**Comment by berbiche** [comment]
@colemickens second ping

**Comment by colemickens** [comment]
I'll try to get to this tomorrow. Thanks for the pings.

**Comment by colemickens** [comment]
Is there an open PR for the `egl-dmabuf` work?

**Comment by colemickens** [comment]
Aha, here we go: https://github.com/obsproject/obs-studio/pull/3338

**Comment by colemickens** [comment]
@berbiche I'll try to preserve your commit authorship and apply this since there's a conflict. Thanks!

**Comment by berbiche** [comment]
You can simply add "Co-authored-by" ¯\_(ツ)_/¯

**Comment by colemickens** [comment]
well, your commit applied cleanly anyway: https://github.com/colemickens/nixpkgs-wayland/commit/3ac16342b4081b364fa810ee5bbfde5b50cf9a99. Hope it's okay. :). I'll go ahead and close this.

**Comment by colemickens** [comment]
and thanks for the contribution, of course, this had flown under my radar.

**Comment by berbiche** [comment]
Thanks for merging this!

**Comment by colemickens** [comment]
Seems like this broke the update script. It's rather brittle.

**Comment by colemickens** [comment]
cc: @berbiche lmk if you can take a look and see if there's a quick solution.

the problem is that the update script loops through the dir entries in `pkgs/` and expects to find a metadata.nix directly under each.

The fix could be as simple as having a "skipped" base package (put skip: true in the metadata.nix), and then having two different obs dirs with the metadata inside. In fact, I'm fairly confident that will work, I can just go ahead and do it myself.

**Comment by berbiche** [comment]
@colemickens 
Sounds like the best solution for the current auto-updater IMO.
Has Niv been considered before to manage dependencies?
Given that deps will never be imported, only the metadata would be used and the cli would handle the rest.

**Comment by colemickens** [comment]
Actually, it's not that simple to fix currently. I'm probably going to revert this.

I'm not convinced `niv` would actually help much here. Last I checked it was also very tied to Git and GitHub which won't fly. Using a token isn't a problem (though I don't know it requires a token, it would be doing the same things my update script does...)

**Comment by colemickens** [comment]
I may be entirely wrong about `niv`, by the way - I would certainly entertain an Issue discussing adopting `niv`. Doesn't have to be huge but at least ensuring that it covers what the current update process covers.

I think there's room for another Nix tool to help here, but I'm already drowning in Nix side projects.

**Comment by berbiche** [comment]
Hey, sorry for the late reply, I will take a look at this when I have time.

Also, based on Niv's readme, it does support random URLs with templates. This does limit it to the HTTP protocol, sadly, but I don't think this is a problem?

**Comment by colemickens** [comment]
@berbiche I resolved the issue here, you can look at the commit history if you want to see what I did (it's spread across a few commits before I got it quite right).

RE: `niv`: please open a new issue so we can track, if I can remove some bash/update.sh, I'd be grateful. Thanks!

**Pull request closed without merging**
