### PR TITLE
WIP Demo configuration for #33

### PR DESCRIPTION
**Pull request by zimbatm**
This is the configuration that I am using more or less.

Since this is also touching the home configuration, a new "demo" user is
created.

### CODE REVIEW

**Comment by colemickens** [comment]
@zimbatm What's the state of this? I've been putting it off since it says WIP and I've been a bit preoccupied with other things. If it's working at least, I'll give it a shot and can review and/or give feedback... thanks!

**Comment by zimbatm** [comment]
The Qemu VM is building and booting, Sway is showing. It's hard to test the key shortcuts from within Sway :)

**Comment by zimbatm** [comment]
So basically it's quite close to be ready and then I got swept away by work.

If you can try the README instructions and report back it would be sweet.

**Comment by zimbatm** [comment]
I never got to a point where these profiles would be useful on their own and the Qemu demo is kinda borked since the Meta key doesn't get captured properly. I think the demo is broken now because it's missing swayidle

**Comment by zimbatm** [comment]
Pushed the swayidle fix and tuned mako a bit. Let's get this merged

**Comment by colemickens** [comment]
I should've squash merged, oops, but it's not a big deal. Thank you @zimbatm !

**Pull request merged**
