### PR TITLE
Swaybg: init package

### PR DESCRIPTION
**Pull request by alexarice**
Fixes issue #141
I have tried to package swaybg pretty much by copying the format for the grim package already in the repository. I have checked that my background now works with this installed to my system. Also have tried to update the `update.sh` file though I'm not sure if I have done this correctly

### CODE REVIEW

**Comment by alexarice** [comment]
Seems to work for png image but not for jpg. The readme says the optional dependency gdk-pixbuf2 should be for this though I can't seem to get it to work

**Comment by colemickens** [comment]
The only question I had was how to package, given that `swaybg` is a REQUIRED package, according to upstream.

Can you, or I will later, open an issue on nixpkgs, tag @primeos and see if they have advice on how to package it? If not this is probably fine to start with.

Thanks a bunch!

**Comment by alexarice** [comment]
I see what you mean. At the moment it appears that if swaybg is not on the system, sway just presents a grey background and everything else seems to work. I'll open the issue though as according to upstream, swaywm 1.1 is imminent so it will also need to be dealt with there as well. 

Do you have any ideas on the gdk-pixbuf thing? I'll keep having a mess around but I've never used meson before so I'm not sure how far I'll get

**Comment by alexarice** [comment]
I've fixed the optional dependencies problem, needed to use `lib.optional gdk_pixbuf` instead of `lib.optional [ gdk_pixbuf ]`
As a side note, the grim package which I copied the derivation from almost certainly doesn't build it's man pages, I'm happy to make a pr for this if that helps

**Comment by colemickens** [comment]
Thanks for this @alexarice!

(If we think of it, we should circle back and mirror nixpkgs upstream changes to the sway/swaybg packages here, if anything ends up changing at the package level. )

**Pull request merged**
