### PR TITLE
imv: resume upgrades

### PR DESCRIPTION
**Pull request by colemickens**
Unskip `imv` and build it with `meson`.

Blocked by https://github.com/eXeC64/imv/issues/228.

### CODE REVIEW

**Comment by berbiche** [comment]
Is this still blocked?

**Comment by colemickens** [comment]
Looks like it's built with `meson` now, and it looks like it's trying to build both backends by default, which is probably not what we want.

I'll probably just wait until `nixpkgs` updates `imv` and then update my derivation from nixpkgs (or just override the src attrs).

**Comment by colemickens** [comment]
in case someone wants to continue: https://github.com/colemickens/nixpkgs-wayland/tree/imv

**Comment by colemickens** [comment]
closing this, we're going to just override the upstream derivation.

**Pull request closed without merging**
