### PR TITLE
update: fmt, mako, sway-bar, waybar, wlroots

### PR DESCRIPTION
**Pull request by colemickens**
Signed-off-by: Cole Mickens <cole.mickens@gmail.com>

### CODE REVIEW

**Comment by colemickens** [comment]
I'm holding off merging, since `wlroots` is not building against `nixpkgs-unstable`.

I assume this failure will wind up in `nixos-unstable` soon. I'll fix it then, unless someone wants to send a fix earlier.

**Comment by bbigras** [comment]
Any progress?

**Comment by bbigras** [comment]
> Sorry for the huge delay here.

Hey no problems. I still enjoy using Sway a lot thanks to you.

Can't we use rust nightly? I'm not sure if there's a downside. I use nightly in production for many projects.

**Comment by colemickens** [comment]
@bbigras I'm not opposed at all, especially since I think it's just `wmfocus` and this would presumably be a short-term thing. I've drug my feet on doing this because I want to learn more about nixpkgs's staging workflow so I can see how far out stable is from landing, but I'd certainly merge a change moving to nightly for `wmfocus`.

**Comment by colemickens** [comment]
Update: The rust update has landed in `nixos-unstable`, but not `nixpkgs-unstable` due to an infrastructure issue. This should resolve itself over night and I can proceed with a full normal update of all packages. Since, I've had to do a number of other things: patching, removing old patches, carrying an old wlroots, I'm going to open a new branch + PR and close this one out.

Thanks for the patience y'all. In the future I'll consider carrying more patches/workarounds to avoid such lengthy durations without updates...

**Pull request closed without merging**
